### PR TITLE
fix: allow lambda put

### PR DESCRIPTION
**Pull request by SPlanzer**
allow the lambda function to access the bucket

### CODE REVIEW

**Comment by SPlanzer** [comment]
I have tested this in the dev environment and as Blayne pointed out in slack this was require to allow the lambda function to publish to s3. 
Testing needs a look at why this passed but from memory its mostly mocks

**Review by blacha — APPROVED** [review]

**Comment by billgeo** [comment]
Looks okay to me. But can we have a test for this?

**Comment by billgeo** [comment]
You okay to merge and deploy this @SPlanzer ?

**Review by billgeo — APPROVED** [review]
LGTM

**Pull request merged**
