### PR TITLE
cd sys tests

### PR DESCRIPTION
**Pull request by SPlanzer**
sys test to confirm correct function of API after deploy

This includes CI/CD integrate which is enabled only against CD for development.
These see tests against API for development deployment but not production. 

tests passing - https://github.com/linz/qgis-plugin-repository/runs/665110480?check_suite_focus=true

### CODE REVIEW

**Comment by billgeo** [comment]
Hi @SPlanzer has this PR been superceded by something else?

**Comment by billgeo** [comment]
Hey @SPlanzer. Tempted to just merge this. Any reason why not to?

**Comment by SPlanzer** [comment]
> Hey @SPlanzer. Tempted to just merge this. Any reason why not to?

These changes run CD so there is elevated risk

What is the status around this product? is there a plan to release?

These changes only serve a purpose under release conditions. I think for this reason as well as Blayne raising some concerns, it should be reviewed when development is next active. This will allow someone to get up to speed with what has been implement here and what is needed. 

Open to discussing other options...

**Comment by billgeo** [comment]
> These changes run CD so there is elevated risk

Isn't this just adding some tests to an existing workflow? Doesn't look like there's any deployment changes here? Still looks like it require a specific tag to release to prod?

**Pull request merged**
